apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: development
nameSuffix: -dev
resources:
  - ../base/
patches:
  - target:
      kind: Ingress
      name: web-ingress
    path: ingress-patch.json
replicas:
  - name: web-deployment
    count: 1
images:
  - name: registry.git.willperry.net/set-time/web
    newTag: 0.7.15-ci.744 # {"$imagepolicy": "set-time:web-ci-image-policy:tag"}
