apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
  namespace: set-time
spec:
  secretName: web--cert
  issuerRef:
    name: letsencrypt
  commonName: "setti.me"
  dnsNames:
    - setti.me
    - "*.setti.me"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: set-time
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: gitlab-registry-token
      containers:
        - name: set-time
          image: registry.git.willperry.net/set-time/web:0.4.6
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: set-time
spec:
  selector:
    app: web
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: set-time
spec:
  ingressClassName: traefik-external
  rules:
    - host: setti.me
      http:
        paths:
          - backend:
              service:
                name: web-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - setti.me
      secretName: web-cert
