apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: production
resources:
  - ../base/
patches:
  - target:
      kind: Ingress
      name: web-ingress
    path: ingress-patch.json
replicas:
  - name: web-deployment
    count: 3
images:
  - name: registry.git.willperry.net/set-time/web
    newTag: 0.7.20 # {"$imagepolicy": "set-time:web-live-image-policy:tag"}
