apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: set-time

commonLabels:
  app: set-time-web
  environment: production

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
